/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("players").del();
  await knex("players").insert([
    {
      id: 1,
      team_id: 1,
      player_name: "Carson Murphy",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player1@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 2,
      team_id: 1,
      player_name: "Theodore Gonzalez",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player2@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 3,
      team_id: 1,
      player_name: "Daniel Anderson",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player3@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 4,
      team_id: 1,
      player_name: "Wyatt Scott",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player4@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 5,
      team_id: 1,
      player_name: "Jack Perez",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player5@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 6,
      team_id: 1,
      player_name: "Leonardo Rivera",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player6@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 7,
      team_id: 1,
      player_name: "Amir Adams",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player7@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 8,
      team_id: 1,
      player_name: "Jackson Moore",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player8@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 9,
      team_id: 1,
      player_name: "Joseph Lewis",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player9@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 10,
      team_id: 1,
      player_name: "John Torres",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player10@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 11,
      team_id: 1,
      player_name: "Liam Smith",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player11@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 12,
      team_id: 2,
      player_name: "Noah Johnson",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player12@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 13,
      team_id: 2,
      player_name: "Oliver Williams",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player13@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 14,
      team_id: 2,
      player_name: "Elijah Brown",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player14@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 15,
      team_id: 2,
      player_name: "William Jones",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player15@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 16,
      team_id: 2,
      player_name: "James Garcia",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player16@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 17,
      team_id: 2,
      player_name: "Benjamin Miller",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player17@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 18,
      team_id: 2,
      player_name: "Lucas Davis",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player18@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 19,
      team_id: 2,
      player_name: "Henry Rodriguez",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player19@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 20,
      team_id: 2,
      player_name: "Alexander Martinez",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player20@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 21,
      team_id: 2,
      player_name: "Mason Hernandez",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player21@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 22,
      team_id: 2,
      player_name: "Michael Lopez",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player22@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 23,
      team_id: 3,
      player_name: "Ethan Wilson",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player23@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 24,
      team_id: 3,
      player_name: "Jacob Thomas",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player24@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 25,
      team_id: 3,
      player_name: "Logan Taylor",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player25@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 26,
      team_id: 3,
      player_name: "Sebastian Lee",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player26@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 27,
      team_id: 3,
      player_name: "Aiden White",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player27@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 28,
      team_id: 3,
      player_name: "Owen Harris",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player28@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 29,
      team_id: 3,
      player_name: "Samuel Clark",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player29@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 30,
      team_id: 3,
      player_name: "Matthew Ramirez",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player30@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 31,
      team_id: 3,
      player_name: "Levi Walker",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player31@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 32,
      team_id: 3,
      player_name: "Mateo Robinson",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player32@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 33,
      team_id: 3,
      player_name: "David Young",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player33@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 34,
      team_id: 4,
      player_name: "Asher King",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player34@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 35,
      team_id: 4,
      player_name: "Julian Allen",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player35@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 36,
      team_id: 4,
      player_name: "Carter Wright",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player36@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 37,
      team_id: 4,
      player_name: "Oscar Nguyen",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player37@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 38,
      team_id: 4,
      player_name: "Landon Hill",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player38@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 39,
      team_id: 4,
      player_name: "Caleb Baker",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player39@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 40,
      team_id: 4,
      player_name: "Theodore Gonzalez",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player40@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 41,
      team_id: 4,
      player_name: "Ryan Nelson",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player41@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 42,
      team_id: 4,
      player_name: "Isaiah Carter",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player42@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 43,
      team_id: 4,
      player_name: "Nathan Mitchell",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player43@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 44,
      team_id: 4,
      player_name: "Cameron Roberts",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player44@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 45,
      team_id: 5,
      player_name: "Maverick Cook",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player45@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 46,
      team_id: 5,
      player_name: "Colton Rivera",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player46@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 47,
      team_id: 5,
      player_name: "Ezra Morales",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player47@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 48,
      team_id: 5,
      player_name: "Cooper Price",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player48@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 49,
      team_id: 5,
      player_name: "Ian Bell",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player49@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 50,
      team_id: 5,
      player_name: "Jaxson Bailey",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player50@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 51,
      team_id: 5,
      player_name: "Santiago Brooks",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player51@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 52,
      team_id: 5,
      player_name: "Francisco Diaz",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player52@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 53,
      team_id: 5,
      player_name: "Caleb Foster",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player53@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 54,
      team_id: 5,
      player_name: "Caden Ortiz",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player54@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
    {
      id: 55,
      team_id: 5,
      player_name: "Emmett Reid",
      address: "112 california drive",
      city: "San Francisco",
      country: "USA",
      contact_name: "Mary Freidman",
      contact_phone: "9919919988",
      player_phone: "5564453424",
      player_email: "player55@prim.com",
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
    },
  ]);
};
